In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_parquet('../data/dados_modelo/municipio_agregado_outras_fontes.parquet')
df.head()

,ano,id_municipio,id_municipio_nome,serie,chave_rede,rede,taxa_alfabetizacao_mun,media_portugues,sigla_uf,taxa_alfabetizacao_uf,indice_analf,MEDIA_INSE
0,<NA>,5101837,None,None,None,None,NaN,NaN,MT,NaN,8.46,NaN
1,2023,1100205,Porto Velho,2° ano do Ensino Fundamental,2,Estadual,57.45,747.2139,RO,58.65,4.36,4.959
2,2023,1100205,Porto Velho,2° ano do Ensino Fundamental,5,Pública (Estadual e Municipal),64.47,760.4047,RO,64.60,4.36,4.892
3,2023,1100205,Porto Velho,2° ano do Ensino Fundamental,3,Municipal,65.06,761.5118,RO,65.17,4.36,4.789
7,2023,1100338,Nova Mamoré,2° ano do Ensino Fundamental,3,Municipal,63.02,754.3625,RO,65.17,9.31,4.733

In [3]:
df.describe()

,ano,taxa_alfabetizacao_mun,media_portugues,taxa_alfabetizacao_uf,indice_analf,MEDIA_INSE
count,11547.0,11547.000000,11547.000000,11547.000000,11568.000000,11498.000000
mean,2023.0,60.705726,750.573209,56.698075,11.795609,4.845077
std,0.0,19.960233,24.109449,11.308461,7.573423,0.483900
min,2023.0,2.120000,673.298300,30.570000,0.900000,3.271000
25%,2023.0,46.830000,735.146800,51.120000,5.520000,4.410000
50%,2023.0,61.410000,749.717200,58.740000,9.490000,4.901500
75%,2023.0,75.690000,763.760800,63.430000,17.970000,5.242000
max,2023.0,100.000000,868.455400,84.490000,36.810000,6.276000

In [4]:
# Tivemos a ideia de criar uma feature não-linear

inse = df['MEDIA_INSE']
analf = df['indice_analf']
    
# Criar a nova variável não-linear
df['razao_inse_analf'] = np.divide(inse, analf + 1e-5)

In [5]:
# Precisamos entender o desvio socioeconômico local
df['raz_alfab_mun_uf'] = np.divide(df['taxa_alfabetizacao_mun'], df['taxa_alfabetizacao_uf'])

In [6]:
df['razao_taxa_uf_inse'] = np.divide(df['taxa_alfabetizacao_uf'],df['MEDIA_INSE']+0.001)

In [7]:
df.to_parquet('../data/dados_modelo/municipio_eng_feat.parquet')